# Generated by Django 4.1.2 on 2022-12-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_shipment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
